#!/bin/sh

##
# Runit run script for the terrain server
#

# Ensure the data directory exists
if [ ! -d /data/tilesets/terrain ]; then
    echo "The /data/tilesets/terrain directory must be present" >&2
    exit 1
fi

# Run the server
exec /sbin/setuser daemon /usr/local/bin/terrain-server -port 8000 -memcached "${MEMCACHED}" -dir /data/tilesets/terrain 2>&1
