#!/bin/sh

##
# Runit run script for the terrain server
#

TILESET_DIR=/data/tilesets/terrain

# Ensure the data directory exists
if [ ! -d "${TILESET_DIR}" ]; then
    echo "The ${TILESET_DIR} directory must be present" >&2
    exit 1
fi

#  Decide whether to serve up static cesium js assets
if [ "${SERVE_STATIC}" = "0" ]
then
    WEB_DIR=""
elif [ -z "${WEB_DIR}" ]
then
    # If no static directory is specified, use the default
    WEB_DIR="/var/www/cesium"
fi

# Decide on the log level
[ -z "${LOG_LEVEL}" ] && LOG_LEVEL="notice"

if [ "${LOG_REQUESTS}" = "0" ]
then
    NO_REQUEST_LOG="true"
else
    NO_REQUEST_LOG="false"
fi

# Decide on the base terrain path
[ -z "${BASE_TERRAIN_PATH}" ] && BASE_TERRAIN_PATH="/tilesets"

# Run the server
exec /sbin/setuser daemon /usr/local/bin/cesium-terrain-server \
    -port=8000 \
    -memcached="${MEMCACHED}" \
    -dir="${TILESET_DIR}" \
    -web-dir="${WEB_DIR}" \
    -base-terrain-url="${BASE_TERRAIN_PATH}" \
    -log-level="${LOG_LEVEL}" \
    -no-request-log="${NO_REQUEST_LOG}" \
    2>&1
